import React from 'react';

const TermsOfUse = () => {
    return (
        <div>
            <h1>

                Terms & Conditions
                Welcome to anbupriyal.in . In order to use the anbupriyal.in Site ("Site"), you must Register as a member of the Site ("Member") and agree to be bound by these Terms of Use ("Agreement"). If you wish to become a Member and communicate with other Members and make use of the service ("Service"), read these Terms of Use and follow the instructions in the Registration process. This Agreement sets out the legally binding terms for your membership. This Agreement may be modified by anbupriyal.in from time to time effective upon notice to you as a Member. Whenever there is a change in the Terms of Use, anbupriyal.in will intimate you of such change. Your continued use of the Site pursuant to such change will constitute deemed acceptance of such changes.

                1. Eligibility.
                You must be at least 18 years of age or over to Register as a member of anbupriyal.in or use this Site. Membership to the Site is void where prohibited. Your use of this Site represents and warrants that you have the right, authority, and capacity to enter into this Agreement and to abide by all of the terms and conditions of this Agreement. This site is not meant to encourage and/or promote illicit sexual relations or extra marital affairs. If anbupriyal.in discovers or becomes aware that any member is using this site to promote or engage or indulge in illicit sexual relations or extra marital affairs his/her membership will be terminated forthwith without any refund and without any liability toanbupriyal.in . anbupriyal.in 's discretion to terminate shall be final and binding.

                2. Term.
                This Agreement will remain in full force and effect while you use the Site and/or are a Member of anbupriyal.in . You may terminate your membership at any time, for any reason by informing anbupriyal.in in writing to terminate your Membership. In the event you terminate your membership, you will not be entitled to a refund of any unutilized subscription fees. anbupriyal.in may terminate your access to the Site and/or your membership for any reason which shall be effective upon sending notice of termination to you at the email address you provide in your application for membership or such other email address as you may later provide to anbupriyal.in . If anbupriyal.in terminates your membership because of your breaching the Agreement, you will not be entitled to any refund of any unused Subscription fees. Even after this Agreement is terminated, certain provisions will remain in effect including sections 4,5,7,9 -12, inclusive, of this Agreement.

                3. Non-Commercial Use by Members.
                The anbupriyal.in Site is for the personal use of individual members only, and may not be used in connection with any commercial endeavors. This includes providing links to other websites, whether deemed competitive to anbupriyal.in or otherwise. Organizations, companies, and/or businesses may not become Members of anbupriyal.in and should not use the anbupriyal.in Service or Site for any purpose. Illegal and/or unauthorized uses of the Site, including unauthorized framing of or linking to the Site will be investigated, and appropriate legal action will be taken, including without limitation, civil, criminal, and injunctive redress.

                4. Other Terms of Use by Members.
                You may not engage in advertising to, or solicitation of, other Members to buy or sell any products or services through the Service. You will not transmit any chain letters or junk email to other anbupriyal.in Members. Although anbupriyal.in cannot monitor the conduct of its Members on the anbupriyal.in Site, it is also a violation of this Agreement to use any information obtained from the Service in order to harass, abuse, or harm another person, or in order to contact, advertise to, solicit, or sell to any Member without their prior explicit consent. In order to protect anbupriyal.in and/or our Members from any abuse/misuse, anbupriyal.in reserves the right to restrict the number of communications/profile contacts & responses/emails which a Member may send to other Member(s) in any 24-hour period to a number which anbupriyal.in deems appropriate in its sole discretion. You will not send any messages to other Members that are obscene, lewd, licentious, and defamatory, promote hatred and/or are racial or abusive in any manner. Transmission of any such messages shall constitute a breach of this Agreement and anbupriyal.in Shall be entitled to terminate your membership forthwith. anbupriyal.in reserves the right to screen messages that you may send to other Member(s) and also regulate the number of your chat sessions in its sole discretion.
                You may not use any automated processes, including IRC Bots, EXE's, CGI or any other programs/scripts to view content on or communicate/contact/respond/interact with anbupriyal.in and/or its Members
                anbupriyal.in owns and retains all proprietary rights, including without limitation, all intellectual property rights in the anbupriyal.in Site and the anbupriyal.in Service. The Site contains the copyrighted material, trademarks, and other proprietary information of anbupriyal.in , and its licensors. Except for that information which is in the public domain or for which you have been given express permission by anbupriyal.in , you may not copy, modify, publish, transmit, distribute, perform, display, or sell any such proprietary information. All lawful, legal and non-objectionable messages (in the sole discretion of anbupriyal.in ), content and/or other information, content or material that you post on the forum boards shall become the property of anbupriyal.in . anbupriyal.in reserves the right to scrutinize all such information, content and/or material posted on the forum boards and shall have the exclusive right to either remove, edit and/or display such information, material and/or content
                You understand and agree that anbupriyal.in may delete any content, messages, photos or profiles (collectively, "Content") that in the sole judgment of anbupriyal.in violates this Agreement or which might be offensive, illegal, defamatory, obscene, libelous, or that might violate the rights, harm, or threaten the safety of other anbupriyal.in Members.
                You are solely responsible for the Content that you publish or display (hereinafter, "post") on the Site through the anbupriyal.in Service, or transmit to other anbupriyal.in Members. anbupriyal.in reserves the right to verify the authenticity of Content posted on the Site. In exercising this right, anbupriyal.in may ask you to provide any documentary or other form of evidence supporting the Content you post on the Site. If you fail to produce such evidence, or if such evidence does not in the reasonable opinion of anbupriyal.in establish or justify the claim, anbupriyal.in may, in its sole discretion, terminate your Membership without a refund of your subscription fees
                By posting Content to any public area of anbupriyal.in , you automatically grant, and you represent and warrant that you have the right to grant, to anbupriyal.in , and other anbupriyal.in Members, an irrevocable, perpetual, non-exclusive, fully-paid, worldwide license to use, copy, perform, display, and distribute such information and content and to prepare derivative works of, or incorporate into other works, such information and content, and to grant and authorize sublicenses of the foregoing.
                5. Content Posted on the Site.
                The following is a partial list of the kind of Content that is illegal or prohibited on the Site. anbupriyal.in will investigate and take appropriate legal action in its sole discretion against anyone who violates this provision, including without limitation, removing the offending communication from the Service and the Site and terminating the Membership of such violators without a refund. It includes (but is not limited to) Content that:
                Newly created profile will be checked for correctness and will be immediately activated after quality declaration verify by anbupriyal.in.
                anbupriyal.in reserves the rights to discontinue, deactivate, or terminate profile if the profile in terms of bad manners and the profile contents are not acceptable if it contains violent language or wrong material.
                You are only liable for your connections with other members through anbupriyal.in.
                Contact information of member's profile will display only to paid members. Free membership is for limited time. anbupriyal.in reserves right to discontinue free membership at any time.
                Members agree that they are legally eligible to get married as far as the age is concerned. anbupriyal.in will not be responsible for misuse of any facility/service it provides, which is in violation to the local government laws.
                Every member submitting his/her matrimonial profile is required to give all the facts essential for establishing a marital relation. Concealing facts relevant to marriage could result in loss or damage to any individual and for which, anbupriyal.incannot be held responsible in any which way.
                anbupriyal.in in no way guarantees the genuineness of the information provided by its members.
                Members will not have any claim against anbupriyal.infor any time delay in posting their information into anbupriyal.in website due to any technical reasons.
                anbupriyal.in is not liable for damages caused due to incorrectness of the information provided by its members regarding the religion, caste or creed or any other personal information. If the members' profile is deemed to be unfit, anbupriyal.in has the right to delete, alter or refuse the same at any point of time without any notice.
                anbupriyal.in cannot be held responsible for any loss or damage resulting from discontinuation of the service. anbupriyal.in will also not be responsible for any damage caused due to others accessing members profile.
                anbupriyal.in cannot guarantee that you as an applicant will receive responses and hence cannot be held responsible for no replies. In this case we cannot give any refunds or credits.
                anbupriyal.in is not legally responsible for any delay in operation due to technical or other reasons.
                Harasses or advocates harassment of another person;
                Involves the transmission of "junk mail", "chain letters," or unsolicited mass mailing or "spamming";
                Promotes information that the person posting it is aware that it is false, misleading or promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libelous;
                Promotes an illegal or unauthorized copy of another person's copyrighted work, such as providing pirated computer programs or links to them, providing information to circumvent manufacture-installed copy-protect devices, or providing pirated music or links to pirated music files;
                Contains restricted or password only access pages, or hidden pages or images (those not linked to or from another accessible page) ;
                Displays pornographic or sexually explicit material of any kind;
                Provides material that exploits people under the age of 18 years in a sexual or violent manner, or solicits personal information from anyone under the age of 18 years;
                Provides instructional information about illegal activities such as making or buying illegal weapons, violating someone's privacy, or providing or creating computer viruses;
                Solicits passwords or personal identifying information for commercial or unlawful purposes from other users / Members; and
                Engages in commercial activities and/or sales without the prior written consent anbupriyal.in Such as contests, sweepstakes, barter, advertising, and pyramid schemes.
                Encourages, invites or solicits extra marital affairs.
                You must use the anbupriyal.in Service in a manner consistent with any and all applicable local, state, and federal laws and regulations.
                If at any time anbupriyal.in is of the view in its sole discretion that your profile contains any information or material or content which is objectionable, unlawful or illegal, Fropper has the right in its sole discretion to either forthwith terminate your membership without refund of your subscription fees or delete such objectionable, illegal or unlawful information, material or content from your profile and allow you to continue as a Member.
                6. Copyright Policy.
                You may not post, distribute, or reproduce in any way any copyrighted material, trademarks, or other proprietary information without obtaining the prior written consent of the owner of such proprietary rights. Without limiting the foregoing, if you believe that your work has been copied and posted on the Site through the anbupriyal.in Service in a way that constitutes copyright infringement, please provide our Copyright Agent with the following information: an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest; a description of the copyrighted work that you claim has been infringed; a description of where the material that you claim is infringing is located on the Site; your address, telephone number, and email address; a written statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; and where applicable a copy of the registration certificate proving registration of copyright or any other applicable intellectual property right; a statement by you, made under penalty of perjury, that the above information in your Notice is accurate and that you are the copyright owner or authorized to act on the copyright owner's behalf. anbupriyal.in 's Copyright Agent for Notice of claims of copyright infringement can be reached by writing to the Mumbai address located under the Help/Contact section on the site.

                7. Member Disputes.
                You are solely responsible for your interactions with other anbupriyal.in Members. anbupriyal.in reserves the right, but has no obligation, to monitor disputes between you and other Members.

                8. Privacy.
                Use of the anbupriyal.in Site and/or the anbupriyal.in Service is governed by the anbupriyal.in Privacy Policy.

                9. Disclaimers.
                anbupriyal.in is not responsible for any incorrect or inaccurate Content posted on the Site or in connection with the anbupriyal.in Service, whether caused by users visiting the Site, Members or by any of the equipment or programming associated with or utilized in the Service, nor for the conduct of any user and/or Member of the anbupriyal.in Service whether online or offline. anbupriyal.in assumes no responsibility for any error, omission, interruption, deletion, defect, delay in operation or transmission, communications line failure, theft or destruction or unauthorized access to, or alteration of, user and/or Member communications. anbupriyal.in is not responsible for any problems or technical malfunction of any telephone network or lines, computer on-line-systems, servers or providers, computer equipment, software, failure of email or players on account of technical problems or traffic congestion on the Internet or at any website or combination thereof, including injury or damage to users and/or Members or to any other person's computer related to or resulting from participating or downloading materials in connection with the anbupriyal.in Site and/or in connection with the anbupriyal.in Service. Under no circumstances will anbupriyal.in be responsible for any loss or damage to any person resulting from anyone's use of the Site or the Service and/or any Content posted on the anbupriyal.in Site or transmitted to anbupriyal.in Members. The exchange of profile(s) through or by anbupriyal.in Should not in any way be construed as any offer and/or recommendation from/by anbupriyal.in . anbupriyal.in Shall not be responsible for any loss or damage to any individual arising out of, or subsequent to, relations established pursuant to the use of anbupriyal.in . The Site and the Service are provided "AS-IS AVALIABLE BASIS" and anbupriyal.in expressly disclaims any warranty of fitness for a particular purpose or non-infringement. anbupriyal.in cannot guarantee and does not promise any specific results from use of the Site and/or the anbupriyal.in Service.

                10. Limitation on Liability.
                Except in jurisdictions where such provisions are restricted, in no event will anbupriyal.in be liable to you or any third person for any indirect, consequential, exemplary, incidental, special or punitive damages, including also lost profits arising from your use of the Site or the anbupriyal.in Service, even if anbupriyal.in has been advised of the possibility of such damages. Notwithstanding anything to the contrary contained herein, anbupriyal.in , liability to you for any cause whatsoever, and regardless of the form of the action, will at all times be limited to the amount paid, if any, by you to anbupriyal.in , for the Service during the term of membership.

                11. Disputes.
                If there is any dispute about or involving the Site and/or the Service, by using the Site, you agree that the dispute will be governed by the laws of India. You agree to the exclusive jurisdiction to the courts of Mumbai, India.

                12. Indemnity.
                You agree to indemnify and hold anbupriyal.in , its subsidiaries, directors, affiliates, officers, agents, and other partners and employees, harmless from any loss, liability, claim, or demand, including reasonable attorney's fees, made by any third party due to or arising out of your use of the Service in violation of this Agreement and/or arising from a breach of these Terms of Use and/or any breach of your representations and warranties set forth above.

                Other.
                By becoming a Member of the Site / anbupriyal.in Service, you agree to receive certain specific emails from anbupriyal.in .
                This Agreement, accepted upon use of the Site and further affirmed by becoming a Member of the anbupriyal.in Service, contains the entire agreement between you and anbupriyal.in regarding the use of the Site and/or the Service. If any provision of this Agreement is held invalid, the remainder of this Agreement shall continue in full force and effect.
                You are under an obligation to report any misuse or abuse of the Site. If you notice any abuse or misuse of the Site or any thing which is in violation of this Agreement, you shall forthwith report such violation to anbupriyal.in by writing to Customer Care. On receipt of such complaint, anbupriyal.in may investigate such complaint and if necessary may terminate the membership of the Member responsible for such violation abuse or misuse without any refund of subscription fee. Any false complaint made by a Member shall make such Member liable for termination of his / her membership without any refund of the subscription fee.
                Please contact us with any questions regarding this Agreement.   </h1>
        </div>
    );
};

export default TermsOfUse;