export const tamil = {
  Name: "பெயர்",
  Email: "மின்னஞ்சல்",
  ProfileImage: "புகைப்படம்",
  Gender: "பாலினம்",
  Height: "உயரம்",
  Weight: "எடை",
  Colour: "நிறம்",
  "Marital Status": "திருமண நிலை",
  "Birth Details": "பிறப்பு விவரங்கள் ",
  Dob: "பிறந்த தேதி",
  Time: "நேரம்",
  Day: "நாள்",
  Place: "இடம்",
  "Professional Details": "தொழில் விவரங்கள்",
  "Work status": "வேலை நிலை",
  Education: "கல்வி",
  Job: "வேலை",
  Income: "வருமானம்",
  Location: "இடம்",
  "Family Details": "குடும்ப விவரங்கள்",
  "Father name": "தந்தை பெயர்",
  "Mother name": "தாய் பெயர்",
  "Father job": "தந்தை வேலை",
  "Mother job": "தாய் வேலை",
  'Father alive': "தந்தை உயிருடன் இருக்கிறாரா?",
  "Mother alive": "தாய் உயிருடன் இருக்கிறாரா?",
  Poorvigam: "பூர்விகம்",
  Gothram: "கோத்திரம்",
  Kuladeivam: "குல தெய்வம்",
  Brothers: "சகோதரன்",
  Sisters: "சகோதரி",
  "Married brothers": "திருமணமான சகோதரன்",
  "Married sisters": "திருமணமான சகோதரி",
  Address: "விலாசம்",
  Mobile: "மொபைல்",
  "Astrology Details": "ஜோதிட விவரங்கள் ",
  "Astro Details": "ஜோதிட விவரங்கள் ",
  "Tamil year": "தமிழ் வருடம்",
  "Tamil month": "தமிழ் மாதம்",
  "Tamil date": "தமிழ் தேதி",
  Rasi: "ராசி",
  Nakshatram: "நட்சத்திரம்",
  Patham: "பாதம்",
  Lagnam: "லக்னம்",
  BirthDesai: "பிறந்த தேசி",
  CurrentDesai: "நடப்பு தேசி",
  DesaiYear: "தேசி வருடம்",
  DesaiMonth: "தேசி மாதம்",
  DesaiDate: "தேசி தேதி",
  Img: "படம்",


  "Looking for": "தேடல்",
  Bride: "மணப்பெண்",
  Groom: "மணமகன்",
  nakshatram: "நட்சத்திரம்",

  "Working status": "பணி நிலை",
  "Not working": "பணிபுரியவில்லை",
  "Seeking Work": "வேலை தேடுவோர்",
  "Self-Employed / Business": "சுய தொழில் / வியாபாரம்",
  "Exam Preparation": "தேர்வு தயாரிப்பு",
  "Working": "பணிபுரிபவர்",


  "Marital status": "திருமண நிலை",
  Single: "திருமணமாகாதவர்",
  Widowed: "கைம்பெண்",
  Widower: "கைமகன்",
  Divorced: "விவாகரத்து பெற்றவர்",
  Separated: "பிரிந்து வாழ்பவர்",

  "Profile registered": "பதிவு செய்யப்பட்டது",
  "Last 10 days": "கடந்த 10 நாட்கள்",
  "Last month": "கடந்த மாதம்",
  "Last 3 months": "கடந்த 3 மாதங்கள்",
  "All": "அனைத்தும்",
  Select: "தேர்ந்தெடு",

  Age: "வயது",

  "My profile": "என் சுயவிவரம்",
  "Profile": "சுயவிவரம்",
  "Edit Profile": "சுயவிவரத்தை திருத்து",
  "Logout": "வெளியேறு",
  Dashboard: "டாஷ்போர்டு",
  "No profile available for the filters": "தேவையான தகுதிகளைப் பூர்த்தி செய்யும் சுயவிவரங்கள் எதுவும் இல்லை",
  "Welcome": "வணக்கம்",
  "Click here ": "இங்கே கிளிக் செய்து",

  "to create your profile": "உங்கள் சுயவிவரத்தை உருவாக்குங்கள்",
  "Basic Details": "அடிப்படை விவரங்கள் ",
  Male: "ஆண்",
  Female: "பெண்",
  "Fair": "வெள்ளை",
  "Wheatish": "கோதுமை",
  "Dusky": "சற்று கருப்பு",
  "Black": "கருப்பு",
  colour: "சரும நிறம்",
  "Yes": "ஆம்",
  "No": "இல்லை",
  Desai: "திசை",
  "Current desai": "திசை",
  "Desai year": "வருடம்",
  "Desai month": "மாதம்",
  "Desai date": "நாள்",
  "Profile image": "புகைப்படம்",
  "Astrology image": "ஜாதகம்",
  "Upload image": "படத்தைப் பதிவேற்றவும்",
  "Cancel": "ரத்து செய்யவும்",
  "Save": "சேமிக்கவும்",
  "Please enter values for all the fields": "தயவுசெய்து அனைத்து விவரங்களையும் உள்ளிடவும்",
  Disclaimer: "மறுப்புத் தெரிவிப்பு",
  [`The information in user profiles is provided by the 
  users themselves. Our site does not verify the authenticity 
  of this information and is not responsible for its accuracy. 
  Users are advised to independently verify the details by contacting
   the profile owner directly or through other means. Use this information 
   at your own discretion.`]: `பயனர் சுயவிவரங்களில் உள்ள தகவல்கள் பயனர்களால் தாங்களே வழங்கப்படுகின்றன.
          இந்த தகவல்களின் நம்பகத்தன்மை அல்லது முழுமைத்தன்மை குறித்து எங்கள் தளம் எந்த 
          உத்தரவாதமும் அளிப்பதில்லை.நீங்கள் முக்கியமானதாகக் கருதும் எந்தவொரு தகவலையும்,
          சுயவிவர உரிமையாளரை நேரடியாகத் தொடர்புகொள்வதன் மூலமோ அல்லது வேறு எந்த 
          வழியிலோ சுயமாக சரிபார்க்க வேண்டிய பொறுப்பு உங்களுடையதே.
          இந்த தகவலை உங்கள் சொந்த விருப்பப்படி பயன்படுத்தவும்.`,
  [`File size exceeds the maximum limit of 5MB.`]: "கோப்பின் அளவு அதிகபட்ச 5MB ஐ விட அதிகமாக உள்ளது.",
  [`download as PDF`]: "PDF ஆக பதிவிறக்கம் செய்யவும்"


};
