export const tamil = {
  Name: "பெயர்",
  Email: "மின்னஞ்சல்",
  ProfileImage: "பேரொளி படம்",
  Gender: "பாலினம்",
  Height: "உயரம்",
  Weight: "எடை",
  Colour: "நிறம்",
  "Marital Status": "திருமண நிலை",
  "Birth Details": "பிறப்பு விவரங்கள் ",
  Dob: "பிறந்த தேதி",
  Time: "நேரம்",
  Day: "நாள்",
  Place: "இடம்",
  "Professional Details": "தொழில் விவரங்கள்",
  "Work status": "வேலை நிலை",
  Education: "கல்வி",
  Job: "வேலை",
  Income: "வருமானம்",
  Location: "இடம்",
  "Family Details": "குடும்ப விவரங்கள்",
  "Father name": "தந்தை பெயர்",
  "Mother name": "தாய் பெயர்",
  "Father job": "தந்தை வேலை",
  "Mother job": "தாய் வேலை",
  'Father alive': "தந்தை உயிருடன் இருக்கிறாரா?",
  "Mother alive": "தாய் உயிருடன் இருக்கிறாரா?",
  Poorvigam: "பூர்விகம்",
  Gothram: "கோத்திரம்",
  Kuladeivam: "குல தெய்வம்",
  Brothers: "மகன்கள்",
  Sisters: "மகள்கள்",
  "Married brother": "திருமணமான மகன்கள்",
  "Married sisters": "திருமணமான மகள்கள்",
  Address: "விலாசம்",
  Mobile: "மொபைல்",
  "Astrology Details": "ஜோதிட விவரங்கள் ",
  "Tamil year": "தமிழ் வருடம்",
  "Tamil month": "தமிழ் மாதம்",
  "Tamil date": "தமிழ் தேதி",
  Rasi: "ராசி",
  Nakshatram: "நட்சத்திரம்",
  Patham: "பத்தாம்",
  Lagnam: "லக்னம்",
  BirthDesai: "பிறந்த தேசி",
  CurrentDesai: "நடப்பு தேசி",
  DesaiYear: "தேசி வருடம்",
  DesaiMonth: "தேசி மாதம்",
  DesaiDate: "தேசி தேதி",
  Img: "படம்",
};
